---
title: Demonstration of Confidence Curves for Mean Differences from Tukey's Honest Significant Difference Confidence Intervals
author: David Darmon
output: html_notebook
---

```{r, message = FALSE}

# library(devtools)
# install_github('ddarmon/confcurve')
library(confcurve)

aov.out = aov(breaks ~ tension, data = warpbreaks)
tukey.out = TukeyHSD(aov.out)
show(tukey.out)

aov.out = aov(breaks ~ tension*wool, data = warpbreaks)
tukey.out = TukeyHSD(aov.out)
show(tukey.out)

xlim = c(-40, 40)

confcurve.TukeyHSD(aov.out, which.term = 1, xlim = xlim)
confcurve.TukeyHSD(aov.out, which.term = 3, ncol = 5, xlim = xlim)

confcurve.ScheffeTest(aov.out, which.term = 1, xlim = xlim)
confcurve.ScheffeTest(aov.out, which.term = 3, ncol = 5, xlim = xlim)

```

```{r}

library(userfriendlyscience)
data(warpbreaks)

formula = breaks ~ tension

y = warpbreaks[[as.character(terms(formula)[[2]])]]
x = warpbreaks[[as.character(terms(formula)[[3]])]]

confcurve.GamesHowell(y, x, xlim = c(-40, 40))
confcurve.TukeyHSD(aov.out, xlim = c(-40, 40))
confcurve.oneway(y, x, B = 5000, xlim = c(-40, 40))

# Verify confidence interval:
games.howell(x, y)
oneway(y, x, posthoc = 'games-howell')

```

